// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: shared.proto

package pbshared

import (
	"context"

	bm "github.com/gisvr/wallet/src/lib/net/http/blademaster"
	"github.com/gisvr/wallet/src/lib/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

const ()

type Permission struct {
	Module      string
	Name        string
	Url         string
	Description string
}

var Perms = []Permission{}
